---
output:
  pdf_document:
    latex_engine: xelatex
    template: template.tex
first: Daloha
last: RodriguezMolina
email: daloha.rodriguez_molina@med.uni-muenchen.de
address: "Am Hedernfeld 7, 81375 München"
orcid: 0000-0002-5355-0474
languages: Spanish (native), English (C2), German (C1), French (B1).
programming: |
  | **use:** R, SAS, SPSS, Python.
github: darokun
twitter: darokun
attributes: "goal-driven leadership, resourceful team player, public speaking, organizational & communication skills"
interests: "Epidemiology, reproducible research, open science, online teaching, causality methods, [R-Ladies](https://rladies.org), health and science communication, community-based participatory research"
edu:
  - {degree: PhD candidate, where: Ludwig-Maximilians-Universität München, description_1: "Medical Research: Epidemiology and Public Health, 2017-present", description_2: "**Project:** *Antibiotic resistance in wastewater: Transmission risks in employees and residents around waste water treatment plants (AWARE-WWTP)*" }
  - {degree: MSc, where: Ludwig-Maximilians-Universität München, description_1: "in Epidemiology, Fall 2016, Final grade: 1.71 (Highest: 1.00, Lowest: 4.00)", description_2: "**Thesis**: *Targeted Maximum Likelihood Estimation to Estimate the Effect of an Educational Intervention on the Knowledge about Preventive Measures against Occupational Asthma and Allergies in Bavarian Agriculture Apprentices: a Randomized Trial*"}
  - {degree: MD, where: Universidad del Zulia, description_1: "final grade: 16.80/20.00"}
work:
  - {year: "2016-present", where: Institute and Outpatient Clinic for Occupational, Social and Environmental Medicine, Clinical Center of the Ludwig Maximilian University Munich, Germany, what: "Research Asistant."}
  - {year: 2014-2016, where: Institute and Outpatient Clinic for Occupational, Social and Environmental Medicine, Clinical Centre of the Ludwig Maximilian University Munich, Germany, what: "Student Asistant, IntMOSH."}
  - {year: Fall 2014, where: "Institute for Medical Informatics, Biometry and Epidemiology. Ludwig-Maximilians-University. Munich, Germany", what: "Teaching Assistant, R course"}
  - {year: 2009-2014, where: Endocrine and Metabolic Diseases Research Center. University of Zulia. Maracaibo, Venezuela, what: "Research Assistant"}
  - {year: 2012-2014, where: Global Salud, C.A. Maracaibo, Venezuela, what: "Occupational Health Physician"}
  - {year: 2012-2014, where: Hospitalización Falcón, S.A. Maracaibo, Venezuela, what: "Emergency Department Physician"}
  - {year: 2010-2011, where: Hospital I San Roque, what: "Rural Physician"}
award:
  - {year: 2017, name: "useR Diversity Scholarship"}
  - {year: 2016, name: "First Place, ASPHER's Young Researchers' Forum, European Public Health Conference"}
  - {year: 2015, name: "Dr. Democh Maurmeier Scholarship"}
  - {year: 2008, name: "Fundayacucho Scholarship"}
outreach:
  - {year: 2017, name: "[R-Ladies Munich](https://www.meetup.com/rladies-munich/), co-founder"}
  - {year: 2011, name: "Student Society for the Promotion of the Endocrine and Metabolic Research, president"}
  - {year: 2010, name: "Student Society for the Promotion of the Endocrine and Metabolic Research, publicity coordinator"}
bibliography: my-papers.bib
csl: apa.csl
---

# Select Presentations
\vspace{-0.5cm}

**Primer Simposio Internacional de Investigación en Salud y Seguridad en el Trabajo (LMU and UNC), Bogotá - Colombia, 2017** \fn{Oral Presentation} 

> **Daloha Rodriguez-Molina**, Swaantje Barth, Ronald Herrera, Constanze Rossmann, Katja Radon, Veronika Karnowski, *"Efecto de una intervención educativa para mejorar el conocimiento de medidas preventivas contra asma y alergias ocupacionales utilizando TMLE."*

**ASPHER's Young Researchers' Forum, European Public Health Conference, Vienna - Austria, 2016** \fn{Poster}  

> **Daloha Rodriguez-Molina**, Swaantje Barth, Ronald Herrera, Constanze Rossmann, Katja Radon, Veronika Karnowski, *"Targeted Maximum Likelihood Estimation to Estimate the Effect of an Educa		tional Intervention on the Knowledge about Preventive Measures against Occupational Asthma and 	Allergies in Bavarian Agriculture Apprentices: a Randomized Trial."*

**XXXI World 	Congress of Internal Medicine, Santiago - Chile, 2012** \fn{Poster}  

> **D. Rodríguez-Molina**, E. Rojas, A. Ferrer, A. Espinoza, A. Figueras, D. Zumztein, L. Rincón. 		*“Prevalence of Metabolic Syndrome among adults in a rural community in Venezuela.”*

**Society for Prevention Research, 20th Annual Meeting, Promoting Healthy Living Through Prevention Science, Washington, D.C. - USA, 2012** \fn{Poster} 

> **Daloha Rodríguez-Molina**, Edward Rojas, Judith Faría, Margiori Rodríguez, Ana Nava, Andrea 		Ochoa, *"Drinking patterns characterization in three communities of the Juana de Ávila parish, Maracaibo, Zulia State, Venezuela."*

**I Congress, Latin American Society of Cardiometabolic Syndrome (LASCME), Maracaibo - Venezuela, 2011** \fn{Poster} 

> **Rodríguez-Molina DV**, Rojas ER, Ferrer AJ, Espinoza AC, Figueras AJ, Zumztein DG, Rincón LE, *"Prevalence of Metabolic Syndrome in adults subjects in Pregonero, Uribante District, Táchira 	State, Venezuela."*

**II Congress, Interamerican Society of Diabetes, Puerto La Cruz - Venezuela, 2011** \fn{Oral Presentation} 

> **Daloha Rodríguez-Molina**, *"Tumor Necrosis Factor and Insulin Resistance."*

**II Congress, Interamerican Society of Diabetes, Puerto La Cruz - Venezuela, 2011** \fn{Poster} 

> **Rodríguez-Molina Daloha V.**, Parra V. María G., Ramos R. Nathacha C., Sánchez A. Deysirée 		C., Urribarrí C. Jesica C., Acosta N. Luis A., *"Alcohol consumption patterns in Maracaibo, Vene-		zuela."*

**XIV Student Scientific Meeting “Dr. Herminio Rincón Carroz”. Faculty of Medicine. University of Zulia. Maracaibo - Venezuela, 2010** \fn{Oral Presentation} 

> **Daloha Rodríguez-Molina**, *"Metabolic Syndrome and Adiposopathy."*

**XIII Student Scientific Meeting “Dr. Herminio Rincón Carroz”. Faculty of Medicine. University of Zulia. Maracaibo - Venezuela, 2009** \fn{Oral Presentation} 

> **Daloha Rodríguez-Molina**, *"Overview of the Immune System."*

**V Scientific Meeting of the Physiology Extension Program. Faculty of Medicine. University of Zulia. Maracaibo - Venezuela, 2006** \fn{Oral Presentation} 

> **Daloha Rodríguez-Molina**, Daniela Parra, *"Gene therapy for the Treatment of Cystic Fibrosis."*

# Peer-reviewed Publications 
\vspace{-0.5cm}